Feature photos s3
hatchways/team-flamingo pull request #46
Opened 2020-05-28 00:13 UTC by MalcolmAG

Allows user upload of photos. Still need to add photos to db, but waiting on other components.

2020-05-28 16:07 UTC, bonnieli reviewed
nice! i guess the next step would be to enable multi files :)

2020-05-28 16:07 UTC, bonnieli commented on client/src/pages/Upload.js
> +        <h1>File: {filename}</h1>
maybe avoid using `<h1>` and `<h2>` for a component - reserve these tags for headers of pages :)

2020-06-01 21:53 UTC, tmclean15 reviewed
You probably did it for testing purposes, but before you merge, I would remove the upload.js page. The DropZoneUpload styling could eventually use some work, although not necessary in this PR. To make the component easily usable in other pages, I would remove the "save" button as the page using the component will want to be controlling photo saves on their own form submission. Not exactly sure which approach is best, but the component should expose some way to call handleSave from the parent component. It might also be useful to have a remove option on the files that are listed.

2020-06-01 21:53 UTC, tmclean15 commented on client/src/pages/Upload.js
> +    var formData = new FormData();
Use let instead of var.
```suggestion
    let formData = new FormData();
```

2020-06-01 21:53 UTC, tmclean15 commented on client/src/pages/Upload.js
> +    if (file.name.length > 20) {
This is a fairly small file name, it might be better to make this bigger if we can.

2020-06-01 21:53 UTC, tmclean15 commented on server/util/db/MutableList.py
> +class MutableList(Mutable, list):
We might eventually want a "pop" method to remove photos.

2020-06-01 21:53 UTC, tmclean15 commented on server/util/validation_decorators/validate_files.py
> +def verify_type(file):
I don't see this used anywhere?

2020-06-01 21:53 UTC, tmclean15 commented on client/src/components/DropZoneUpload.js
> +      })}
```suggestion
      {files.map((file, index) => {
        return <p key={index}>{file.name}</p>;
      })}
```

2020-06-01 21:53 UTC, tmclean15 commented on client/src/components/DropZoneUpload.js
> +    var formData = new FormData();
```suggestion
    let formData = new FormData();
```

2020-06-01 21:59 UTC, MalcolmAG commented on client/src/pages/Upload.js
> +    var formData = new FormData();
change made

2020-06-01 22:00 UTC, MalcolmAG commented on server/util/validation_decorators/validate_files.py
> +def verify_type(file):
Just some leftover code

2020-06-01 22:01 UTC, MalcolmAG commented on client/src/components/DropZoneUpload.js
> +    var formData = new FormData();
change made

2020-06-01 22:01 UTC, MalcolmAG commented on client/src/components/DropZoneUpload.js
> +      })}
change made

2020-06-02 20:00 UTC, tmclean15 requested changes
A few minor changes, looks good otherwise.

2020-06-02 20:00 UTC, tmclean15 commented on server/util/validation_decorators/validate_image_files.py
> +            return jsonify({"error": "folder not valid, must be 'project' or 'profile'"}), 400
```suggestion
            return jsonify({"error": "folder not valid, must be 'project' or 'user'"}), 400
```

2020-06-02 20:00 UTC, tmclean15 commented on server/util/validation_decorators/validate_image_files.py
> +        if request.form["project_id"] != "null":
```suggestion
        if request.form["folder"] == "project":
```
We should check that the client provided a project id if they are saving the file to a project.

2020-06-02 20:43 UTC, merged